version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - MONGODB_URI=mongodb://mongo:27017/serviskol
      - JWT_SECRET=supertajnyserviskol
      - PORT=3001
    ports:
      - 3001:3001
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health/health"]
      interval: 30s
      timeout: 10s
      retries: 5
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - 8080:80
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
volumes:
  mongo-data:
