# Backend Dockerfile
FROM node:20-alpine AS deps
WORKDIR /app
COPY backend/package*.json ./
RUN npm install --production=false

FROM node:20-alpine AS prod
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY backend .
RUN npm prune --production
# Vytvoření neprivilegovaného uživatele
RUN addgroup -g 1001 appgroup && adduser -D -u 1001 -G appgroup appuser
USER appuser
EXPOSE 3001
CMD ["npm", "start"]
