name: AI Self-Improvement Report

on:
  schedule:
    - cron: '0 15 1 1,4,7,10 *' # Prvního dne v lednu, dubnu, červenci, říjnu v 15:00
  workflow_dispatch:

jobs:
  ai-self-improvement:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Run ai_self_improvement.js
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: node scripts/ai_self_improvement.js
