name: Audit Rights and Incidents
on:
  schedule:
    - cron: '0 7 * * 1'
  workflow_dispatch:
jobs:
  audit-rights-and-incidents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Run audit workflow
        env:
          SLACK_CRITICAL_CHANNEL: ${{ secrets.SLACK_CRITICAL_CHANNEL }}
        run: node backend/scripts/ai_audit_rights_and_incidents.js
