name: CI
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 7 * * 1'
  workflow_dispatch:
jobs:
  ai-accessibility-review:
    name: AI Accessibility Review
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Install glob
        run: npm install glob
      - name: Run AI accessibility review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: node scripts/ai-accessibility-review.js
      - name: Upload AI accessibility review
        uses: actions/upload-artifact@v4
        with:
          name: ai-accessibility-review
          path: ai-accessibility-review.md
      - name: Slack notification (AI accessibility review)
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: repo,commit,author,action,eventName,ref,workflow
          custom_payload: |
            {
              "text": "*AI Accessibility Review* :wheelchair:\n$(cat ai-accessibility-review.md)"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  ai-test-coverage-review:
    name: AI Test Coverage Review
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Run AI test coverage review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: node scripts/ai-test-coverage-review.js
      - name: Upload AI test coverage review
        uses: actions/upload-artifact@v4
        with:
          name: ai-test-coverage-review
          path: ai-test-coverage-review.md
      - name: Slack notification (AI test coverage review)
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: repo,commit,author,action,eventName,ref,workflow
          custom_payload: |
            {
              "text": "*AI Test Coverage Review* :test_tube:\n$(cat ai-test-coverage-review.md)"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  # ...další AI joby ve stejném stylu...
  frontend:
    name: Frontend lint, test, build, coverage
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm audit --audit-level=moderate
      - run: npm run lint
      - run: npx vitest run
      - run: npm run build
      - run: npm run test:coverage
      - name: Upload frontend coverage
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: ./frontend/coverage
      - name: Upload frontend coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./frontend/coverage/lcov.info
      - name: Slack notification (AI alert)
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: repo,commit,author,action,eventName,ref,workflow
          custom_payload: |
            {
              "text": "*AI Alert Report* :rotating_light:\n$(cat ai-alert-report.md)"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          flags: frontend
          name: frontend-coverage
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
  backend:
    name: Backend lint, test, coverage
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm audit --audit-level=moderate
      - run: npm run lint
      - run: npm test
      - run: npm run test:coverage
      - name: Upload backend coverage
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: ./backend/coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./backend/coverage/lcov.info
          flags: backend
          name: backend-coverage
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
  # ...další CI joby ve stejném stylu...
