name: Onboarding & Lessons Learned Update

on:
  workflow_dispatch:
  schedule:
    - cron: '15 8 * * 1' # Každé pondělí v 8:15

jobs:
  onboarding-lessons-learned-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
        working-directory: ./backend
      - name: Run onboarding & lessons learned update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node scripts/ai_onboarding_lessons_learned_update.js
        working-directory: ./backend
      - name: Commit & push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Automatická aktualizace lessons learned a onboarding checklistů'
          branch: main
          file_pattern: |
            backend/onboarding-lessons-learned.md
            ONBOARDING_CHECKLIST.md
            ONBOARDING_DEV.md
            mobile/ONBOARDING_MOBILE.md
            onboarding-checklist.md
            prompts/AI_MICRO_WORKSHOPS.md
