name: Strategic Audit Issues
on:
  schedule:
    - cron: '0 8 * * 1'
  workflow_dispatch:
jobs:
  create-issues-from-audit:
    name: Create Issues from Audit Reports
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Create Issues from Audit Reports
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node backend/scripts/ai_create_issues_from_audit.js
